apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ai-task-stub
spec:
  description: >-
    This task does a whole lotta nothin
  params:
    - name: time
      description: How long to do nothing
      type: string
  steps:
    - name: ai-build
      image: alpine/git:latest
      script: |
        sleep $(params.time)
