apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifest
spec:
  description: >-
    This task updates the manifest for the current application to point to the image tag created with the short commit.
  workspaces:
    - name: source
  params:
    - name: image
      description: Used to tag the built image.
      type: string
    - name: target-branch
      description: Target branch to push to
      type: string
      default: "main"
    - name: git_user_name
      type: string
      description: Git user name for performing the push operation.
      default: "Tekton Pipeline"
    - name: git_user_email
      type: string
      description: Git user email for performing the push operation.
      default: "tekton@tekton.com"
    - name: deployment_file
      description: File in which the image configuration is stored.
      type: string
    - name: deployment_repo
      description: Repo in which the image configuration is stored.
      type: string
    - default: git-host-access-token
      name: GIT_TOKEN_SECRET_NAME
      type: string
    - default: token
      name: GIT_TOKEN_SECRET_KEY
      type: string
  steps:
    - name: git
      image: alpine/git:latest
      workingDir: $(workspaces.source.path)
      env:
        - name: GITHOSTACCESSTOKEN
          valueFrom:
            secretKeyRef:
              key: $(params.GIT_TOKEN_SECRET_KEY)
              name: $(params.GIT_TOKEN_SECRET_NAME)
 
      script: |
        # Setting up the git config.
        git config --global user.email "$(params.git_user_email)"
        git config --global user.name "$(params.git_user_name)"

        # Checkout target branch to avoid the detached HEAD state
        TMPDIR=$(mktemp -d)

        cd $TMPDIR
        git clone $(params.deployment_repo)
        cd gitops
        git checkout $(params.target-branch)

        # Set to the short commit value passed as parameter.
        # Notice the enclosing " to keep it as a string in the resulting YAML.
        IMAGE=\"$(params.image)\"

        sed -i "#^\(-[[:space:]]*image: \).*#\1${IMAGE}#" $(params.deployment_file)

        git add $(params.deployment_file)
        git commit -m "Automatically updated manifest to point to image tag $IMAGE"
        git push origin $(params.target-branch)