apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: dev-catalog-catalog-binding
  namespace: cicd
spec:
  params:
  - name: imageRepo
    value: quay.io/globex/catalog
  - name: manifestFile
    value: environments/dev/apps/catalog/services/catalog/base/config/100-deployment.yaml
  - name: tlsVerify
    value: "true"
status: {}
