apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: dev-app-inventory-inventory-binding
  namespace: cicd
spec:
  params:
  - name: imageRepo
    value: quay.io/globex/inventory
  - name: tlsVerify
    value: "true"
status: {}
