apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: dev-app-inventory-inventory-binding
  namespace: cicd
spec:
  params:
  - name: imageRepo
    value: quay.io/globex/inventory
  - name: manifestFile
    value: environments/dev/apps/app-inventory/services/inventory/base/config/100-deployment.yaml
  - name: tlsVerify
    value: "true"
status: {}
