apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/part-of: app-catalog
  name: catalog
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/part-of: app-catalog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: catalog
        app.kubernetes.io/part-of: app-catalog
    spec:
      containers:
      - image: quay.io/globex/catalog:latest
        imagePullPolicy: Always
        name: catalog
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
