apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/part-of: app-catalog
    app.openshift.io/runtime: spring
  name: catalog
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/part-of: app-catalog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: catalog
        app.kubernetes.io/part-of: app-catalog
    spec:
      containers:
      - image: quay.io/globex/catalog:main-387b0f7133a1688da393d7c663e4561d5461dbb9
        imagePullPolicy: Always
        name: catalog
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: JAVA_OPTS_APPEND
            value: -Dspring.profiles.active=openshift
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://catalog-database:5432/catalog
          - name: SPRING_DATASOURCE_USERNAME
            value: sa
          - name: SPRING_DATASOURCE_PASSWORD
            value: sa
          - name: INVENTORY_URL
            value: inventory
      serviceAccountName: default
status: {}
