apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: app-gateway
    app.openshift.io/runtime: nodejs
  name: gateway
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/part-of: app-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/part-of: app-gateway
    spec:
      containers:
      - image:  "quay.io/globex/gateway:main-acff78a3003eff7386bab282bc46e518e53d3913"
        imagePullPolicy: Always
        name: gateway
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: COOLSTORE_GW_ENDPOINT
            value: catalog
      serviceAccountName: default
status: {}
